--? 2. MODELO DE DATOS (Oracle 19c)
CREATE TABLE EXCEL_DATA (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    COLUMNA1 VARCHAR2(100),
    COLUMNA2 VARCHAR2(100),
    COLUMNA3 VARCHAR2(100),
    COLUMNA4 VARCHAR2(100)
);

COMMIT;